import org.jetbrains.kotlin.gradle.plugin.mpp.KotlinNativeTarget
import org.jetbrains.kotlin.konan.target.HostManager

plugins {
    id("smtp.kmp.native-host")
}

/**
 * Where OpenSSL 3 lives on this machine.
 *
 * Not written into the `.def` file: Homebrew keeps headers under a versioned prefix and Debian
 * keeps libraries in a multiarch directory, so a hardcoded path breaks on the next upgrade or on
 * the next distribution.
 */
val opensslPrefix: File =
    listOf(
        "/opt/homebrew/opt/openssl@3",
        "/usr/local/opt/openssl@3",
        "/usr",
        "/usr/local",
    ).map(::File)
        .firstOrNull { File(it, "include/openssl/ssl.h").exists() }
        ?: error(
            "OpenSSL 3 headers not found. Install `libssl-dev` (Debian/Ubuntu) or " +
                "`brew install openssl@3` (macOS), then re-run the build.",
        )

/**
 * Every directory the headers actually need.
 *
 * `ssl.h` sits in `include/openssl`, but on Debian multiarch `opensslconf.h` — which `macros.h`
 * includes — lives in `include/<triplet>/openssl` instead. Point cinterop only at the first one
 * and it fails with "'openssl/opensslconf.h' file not found".
 */
val opensslIncludeDirs: List<File> =
    buildList {
        val include = File(opensslPrefix, "include")
        add(include)
        include
            .listFiles()
            ?.filter { it.isDirectory && File(it, "openssl/opensslconf.h").exists() }
            ?.let(::addAll)
    }

/**
 * The directories the shared objects actually live in — `lib` on Homebrew, `lib/<triplet>` on
 * Debian multiarch. Only the ones that hold `libssl` are kept: these paths are written into the
 * published klib, and a consumer has no use for a directory that was merely a candidate here.
 */
val opensslLibDirs: List<File> =
    listOf("lib", "lib/x86_64-linux-gnu", "lib/aarch64-linux-gnu")
        .map { File(opensslPrefix, it) }
        .filter { dir -> dir.listFiles()?.any { it.name.startsWith("libssl.") } == true }
        .ifEmpty {
            error(
                "OpenSSL 3 libraries not found under $opensslPrefix: " +
                    "the headers are there, the shared objects are not.",
            )
        }

/**
 * The cinterop definition with the linker options WRITTEN IN.
 *
 * The source `openssl.def` has none: the paths differ between Homebrew and Debian and are resolved
 * above. But the options must end up in the **klib**, or a consumer gets a library it cannot link —
 * `tools/consumer-check` is that consumer, and it was red against the artefact published without
 * them (M-110). So the definition is generated: the source text plus `linkerOpts` and
 * `libraryPaths` with the values already resolved. Until then the resolution reached only our own
 * binaries, through `binaries.all`, and those are the one place a missing option can never show.
 */
val generatedDefinition: File =
    layout.buildDirectory.file("cinterop/openssl.def").get().asFile.also { file ->
        val source = file("src/nativeInterop/cinterop/openssl.def")
        // Without the `-Wl,` prefix: options from a `.def` go straight to `ld.lld`, not through the
        // compiler driver, and the driver's spelling is rejected there as an unknown argument
        // (measured in mongkn, whose fix this one repeats).
        //
        // The flag itself is not caution. The Kotlin/Native sysroot deliberately ships an old glibc
        // for portable binaries, while the distribution's libssl is built against a newer one and
        // references symbols like stat@GLIBC_2.33; ld.lld treats an unresolved reference inside a
        // foreign shared object as an error. With the flag the dynamic loader resolves them at
        // start-up, against the distribution's own glibc. A consumer links with the same sysroot and
        // the same libssl, so the flag has to travel in the klib as well.
        val allowUndefined = if (HostManager.hostIsLinux) "--allow-shlib-undefined " else ""
        val searchDirs = opensslLibDirs.joinToString(" ") { "-L" + it.absolutePath }
        val libraryPaths = opensslLibDirs.joinToString(" ") { it.absolutePath }
        // Before the `---` line: below it is C, where a `#` is a preprocessor directive.
        val (properties, code) = source.readText().split("\n---\n", limit = 2)
        file.parentFile.mkdirs()
        file.writeText(
            properties +
                """

                # Generated by smtp-tls-openssl/build.gradle.kts; edits here are overwritten.
                #
                # These lines are what makes the klib usable by a consumer: without them it builds and
                # publishes, and fails to link on the other side.
                #
                # The search directory is inside `linkerOpts`, not only in `libraryPaths`, and that is
                # not duplication: `libraryPaths` acts at the cinterop stage and never reaches the
                # consumer's link. With `libraryPaths` alone the error changes from `undefined symbol`
                # to `unable to find library` (measured in mongkn, whose fix this one repeats).
                linkerOpts = $allowUndefined$searchDirs -lssl -lcrypto
                libraryPaths = $libraryPaths
                """.trimIndent() + "\n---\n" + code,
        )
    }

kotlin {
    targets.withType<KotlinNativeTarget>().configureEach {
        compilations.getByName("main").cinterops.create("openssl") {
            definitionFile.set(generatedDefinition)
            includeDirs(*opensslIncludeDirs.toTypedArray())
        }

        // No linker options here any more: all of them are in the generated `.def` and therefore in
        // the klib. While they lived here our own binaries linked and a consumer's did not.
    }

    sourceSets {
        nativeMain.dependencies {
            api(projects.smtpCore)
        }
        nativeTest.dependencies {
            implementation(libs.kotlinx.coroutines.test)
            // Test-only: the TLS tests need a real socket underneath, and that is the transport
            // module's job. Production code here never depends on it.
            implementation(projects.smtpTransportKtor)
            implementation(projects.smtpClient)
        }
    }
}
